url: "https://xiao-chenguang.github.io" # the base hostname & protocol for your site
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-sitemap

title: Chenguang Xiao
logo: photo.png
description: Chenguang is currently a PhD candidate in computer science.
# show_downloads: false
google_analytics: true

collections:
  colleagues:
    # output: false